version: 0.2

phases:
  install:
    commands:
      # Fetch the unique SHA for tagging Docker images
      - SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 396913717156.dkr.ecr.ap-northeast-2.amazonaws.com

  build:
    commands:
      - echo Build started for commit DEV
      - echo Building the Docker image...
      # - docker buildx build --platform linux/amd64 -t harvest_post:dev .  
      - docker build -t harvest_post:dev .  
      - docker tag harvest-post:dev 396913717156.dkr.ecr.ap-northeast-2.amazonaws.com/harvest-post:dev

  post_build:
    commands:
      - echo Build completed for commit DEV
      - echo Pushing the Docker image to ECR...
      - docker push 396913717156.dkr.ecr.ap-northeast-2.amazonaws.com/harvest-post:dev

      # Check if the Lambda function exists to update or create it
      - echo "Running the custom shell script..."
      - chmod +x scripts/create_or_update_lambda_function.sh   # Ensure the script is executable
      - ./scripts/create_or_update_lambda_function.sh     
