version: 0.2

phases:
  install:
    commands:
      # Fetch the unique SHA for tagging Docker images
      - SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 396913717156.dkr.ecr.ap-northeast-2.amazonaws.com

  build:
    commands:
      - echo Build started for commit DEV
      - echo Building the Docker image...
      # - docker buildx build --platform linux/amd64 -t harvest_post:dev .  
      - docker build -t harvest-post:dev .  
      - docker tag harvest-post:dev 396913717156.dkr.ecr.ap-northeast-2.amazonaws.com/harvest-post:dev

  post_build:
    commands:
      - echo Updating lambda function environment variables...
      - |
        MAX_ATTEMPTS=10
        ATTEMPT=0
        FUNCTION_STATE=$(aws lambda get-function --function-name harvest-post --query 'Configuration.State' --output text)
        while [ "$FUNCTION_STATE" != "Active" ] && [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
          echo "Waiting for Lambda function to become Active..."
          sleep 100
          ATTEMPT=$((ATTEMPT+1))
          FUNCTION_STATE=$(aws lambda get-function --function-name havest-post --query 'Configuration.State' --output text)
        done
        if [ "$FUNCTION_STATE" != "Active" ]; then
          echo "Lambda function did not become Active in time. Exiting..."
          sleep 30
        fi

      - echo Build completed for commit DEV
      - echo Pushing the Docker image to ECR...
      - docker push 396913717156.dkr.ecr.ap-northeast-2.amazonaws.com/harvest-post:dev

      # Check if the Lambda function exists to update or create it
      - echo "Running the custom shell script..."
      - chmod +x scripts/create_or_update_lambda_function.sh   # Ensure the script is executable
      - ./scripts/create_or_update_lambda_function.sh     
